//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareMonkeys.SiteStarter.Web.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Language {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Language() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareMonkeys.SiteStarter.Web.Properties.Language", typeof(Language).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Account Details.
		/// </summary>
		public static string AccountDetails {
			get {
				return ResourceManager.GetString("AccountDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to and go to.
		/// </summary>
		public static string AndGoTo {
			get {
				return ResourceManager.GetString("AndGoTo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (asc).
		/// </summary>
		public static string Asc {
			get {
				return ResourceManager.GetString("Asc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (desc).
		/// </summary>
		public static string Desc {
			get {
				return ResourceManager.GetString("Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Index.
		/// </summary>
		public static string Index {
			get {
				return ResourceManager.GetString("Index", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You&apos;re not in the right role to do that..
		/// </summary>
		public static string InvalidRole {
			get {
				return ResourceManager.GetString("InvalidRole", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Loading.
		/// </summary>
		public static string Loading {
			get {
				return ResourceManager.GetString("Loading", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Message.
		/// </summary>
		public static string Message {
			get {
				return ResourceManager.GetString("Message", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string Name {
			get {
				return ResourceManager.GetString("Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You are not signed in..
		/// </summary>
		public static string NotAuthenticated {
			get {
				return ResourceManager.GetString("NotAuthenticated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No tests found..
		/// </summary>
		public static string NoTestsFound {
			get {
				return ResourceManager.GetString("NoTestsFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pages.
		/// </summary>
		public static string Pages {
			get {
				return ResourceManager.GetString("Pages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Register.
		/// </summary>
		public static string Register {
			get {
				return ResourceManager.GetString("Register", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Report Issue.
		/// </summary>
		public static string ReportIssue {
			get {
				return ResourceManager.GetString("ReportIssue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Run.
		/// </summary>
		public static string Run {
			get {
				return ResourceManager.GetString("Run", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Run All Tests.
		/// </summary>
		public static string RunAllTests {
			get {
				return ResourceManager.GetString("RunAllTests", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Send.
		/// </summary>
		public static string Send {
			get {
				return ResourceManager.GetString("Send", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Subject.
		/// </summary>
		public static string Subject {
			get {
				return ResourceManager.GetString("Subject", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Test Fixtures.
		/// </summary>
		public static string TestFixtures {
			get {
				return ResourceManager.GetString("TestFixtures", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to To.
		/// </summary>
		public static string To {
			get {
				return ResourceManager.GetString("To", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You aren&apos;t authorised to do that..
		/// </summary>
		public static string Unauthorised {
			get {
				return ResourceManager.GetString("Unauthorised", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The user was deleted successfully..
		/// </summary>
		public static string UserDeleted {
			get {
				return ResourceManager.GetString("UserDeleted", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The user was updated successfully..
		/// </summary>
		public static string UserUpdated {
			get {
				return ResourceManager.GetString("UserUpdated", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Your account was updated successfully..
		/// </summary>
		public static string YourAccountUpdated {
			get {
				return ResourceManager.GetString("YourAccountUpdated", resourceCulture);
			}
		}
	}
}
