using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("SiteStarter.Entities.Tests")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("SoftwareMonkeys")]
[assembly: AssemblyProductAttribute("SiteStarter.Entities.Tests")]
[assembly: AssemblyCopyrightAttribute("Copyright SoftwareMonkeys (c) 2011")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.6.8.1102")]
[assembly: AssemblyFileVersionAttribute("2.6.8.1102")]

