using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("SiteStarter.Business.Tests")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("SoftwareMonkeys")]
[assembly: AssemblyProductAttribute("SiteStarter.Business.Tests")]
[assembly: AssemblyCopyrightAttribute("Copyright SoftwareMonkeys (c) 2010")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2.6.2.1")]
[assembly: AssemblyFileVersionAttribute("2.6.2.1")]

