using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("SiteStarter.Entities")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("SoftwareMonkeys.net")]
[assembly: AssemblyProductAttribute("SiteStarter.Entities")]
[assembly: AssemblyCopyrightAttribute("Copyright SoftwareMonkeys.net (c) 2009")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.0.6.96")]
[assembly: AssemblyFileVersionAttribute("1.0.6.96")]

