//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareMonkeys.SiteStarter.Web.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Language {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Language() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareMonkeys.SiteStarter.Web.Properties.Language", typeof(Language).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Account Details.
		/// </summary>
		internal static string AccountDetails {
			get {
				return ResourceManager.GetString("AccountDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (asc).
		/// </summary>
		internal static string Asc {
			get {
				return ResourceManager.GetString("Asc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to (desc).
		/// </summary>
		internal static string Desc {
			get {
				return ResourceManager.GetString("Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Index.
		/// </summary>
		internal static string Index {
			get {
				return ResourceManager.GetString("Index", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You&apos;re not in the right role to do that..
		/// </summary>
		internal static string InvalidRole {
			get {
				return ResourceManager.GetString("InvalidRole", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		internal static string Name {
			get {
				return ResourceManager.GetString("Name", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No tests found..
		/// </summary>
		internal static string NoTestsFound {
			get {
				return ResourceManager.GetString("NoTestsFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pages.
		/// </summary>
		internal static string Pages {
			get {
				return ResourceManager.GetString("Pages", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Register.
		/// </summary>
		internal static string Register {
			get {
				return ResourceManager.GetString("Register", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Run.
		/// </summary>
		internal static string Run {
			get {
				return ResourceManager.GetString("Run", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Run All Tests.
		/// </summary>
		internal static string RunAllTests {
			get {
				return ResourceManager.GetString("RunAllTests", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Test Fixtures.
		/// </summary>
		internal static string TestFixtures {
			get {
				return ResourceManager.GetString("TestFixtures", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The user was deleted successfully..
		/// </summary>
		internal static string UserDeleted {
			get {
				return ResourceManager.GetString("UserDeleted", resourceCulture);
			}
		}
	}
}
